### ISSUE TITLE
Setting up development tools

### ISSUE THREAD

**Issue by kiiiyo** [kiiiyo/learn-supabase-web-app#1]
# Overview

Set up development tools

## Task

- [x] Next.js install
- [x] Husky and Linst Staged package install
- [x] Commitlint pakage install
- [x] #3
