### ISSUE TITLE
Make prototype pages

### ISSUE THREAD

**Issue by kiiiyo** [kiiiyo/learn-supabase-web-app#5]
# Overview

Make prototype pages.

## Task

- [ ] Set up style config
- [ ] Set up component config

### Page Component

- [ ] TopPage Component
- [ ] LoginPage Component
- [ ] DashboardPage Component
- [ ] CollectionListPage Component
- [ ] CollectionDetailPage Component
- [ ] ItemListPage Component
- [ ] ItemCreatePage Component
- [ ] ItemDetailPage Component
- [ ] ItemEditPage Component
- [ ] ProfilePage Component
- [ ] ProfileEditPage Component
- [ ] NotFoundPage Component
- [ ] InternalServer ErrorPage Component
- [ ] NoPermissionPage Component
